@startuml

title Collection UML

' 親玉
interface "Collection<E>"{
    +removeIf(Predicate)
}

' 参謀
interface "List<E>" {
    +of()
}
interface "Queue<E>"
interface "Set<E>"

' 参謀見習い
interface "Dequeue<E>"
interface "HashSet<E>"

' 下っ端
class "ArrayList<E>"
class "LinkedList<E>"

' 関係図
"Collection<E>" <|-- "List<E>"
"Collection<E>" <|-- "Queue<E>"
"Collection<E>" <|-- "Set<E>"

"Queue<E>" <|-- "Dequeue<E>"
"Set<E>" <|-- "HashSet<E>"

"List<E>" <|.. "ArrayList<E>"
"List<E>" <|.. "LinkedList<E>"
"Dequeue<E>" <|.. "LinkedList<E>"

@enduml